server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false    #禁用thyme leaf缓存
  rabbitmq:
    host: 192.168.1.100
    username: leyou
    password: leyou
    virtual-host: /leyou

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
